on:
  workflow_call:
    inputs:
      pkg_type:
        required: false
        type: string
      arch:
        required: false
        type: string

defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build ${{ inputs.pkg_type }}-${{ inputs.arch }} package
    runs-on: heavy${{ inputs.arch == 'arm64' && '-arm64' || '' }}
    container: ghcr.io/xrplf/ci/${{ inputs.pkg_type == 'rpm' && 'rhel-9' || 'debian-bookworm' }}:gcc-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build packages
        run: |
          ./pkgs/build.sh
          cat build_vars >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.pkg_type }}-${{ inputs.arch }}
          path: "*${{ inputs.arch }}.${{ inputs.pkg_type }}"
          if-no-files-found: error
